#pragma once
#include <string>

namespace RaisinEng
{
	inline std::string _DebugPanel;
	inline std::string _InfoPanel;
	inline std::string _ErrorPanel;

#define DEBUG_LOG(X)	{_DebugPanel += X;\
					_DebugPanel += '\n';}
#define ERROR_LOG(X)	{_ErrorPanel += X;\
					_ErrorPanel += '\n';}
#define INFO_LOG(X)	{_InfoPanel += X;\
					_InfoPanel += '\n';}
	const int MODEL_LIST_SIZE = 111;
	inline const char* gModelList[MODEL_LIST_SIZE]=
	{
		"2CylinderEngine",
		"ABeautifulGame",
		"AlphaBlendModeTest",
		"AnimatedCube",
		"AnimatedMorphCube",
		"AnimatedMorphSphere",
		"AnimatedTriangle",
		"AntiqueCamera",
		"AttenuationTest",
		"Avocado",
		"BarramundiFish",
		"Bistro",
		"BoomBox",
		"BoomBoxWithAxes",
		"Box",
		"Box With Spaces",
		"BoxAnimated",
		"BoxInterleaved",
		"BoxTextured",
		"BoxTexturedNonPowerOfTwo",
		"BoxVertexColors",
		"BrainStem",
		"Buggy",
		"Cameras",
		"CarbonFibre",
		"CesiumMan",
		"CesiumMilkTruck",
		"ClearCoatCarPaint",
		"ClearcoatRing",
		"ClearcoatSphere",
		"ClearCoatTest",
		"ClearcoatWicker",
		"Corset",
		"Cube",
		"DamagedHelmet",
		"DirectionalLight",
		"DragonAttenuation",
		"Duck",
		"EmissiveStrengthTest",
		"EnvironmentTest",
		"FlightHelmet",
		"Fox",
		"GearboxAssy",
		"GlamVelvetSofa",
		"glTF_RGB_June16.svg",
		"InterpolationTest",
		"IridescenceDielectricSpheres",
		"IridescenceLamp",
		"IridescenceMetallicSpheres",
		"IridescenceSuzanne",
		"IridescentDishWithOlives",
		"Lantern",
		"LightsPunctualLamp",
		"MaterialsVariantsShoe",
		"MeshPrimitiveModes",
		"MetalRoughSpheres",
		"MetalRoughSpheresNoTextures",
		"model-index.json",
		"models.list",
		"MorphPrimitivesTest",
		"MorphStressTest",
		"MosquitoInAmber",
		"MultipleScenes",
		"MultiUVTest",
		"NegativeScaleTest",
		"NormalTangentMirrorTest",
		"NormalTangentTest",
		"OrientationTest",
		"Plane",
		"PrimitiveModeNormalsTest",
		"README.md",
		"ReciprocatingSaw",
		"RecursiveSkeletons",
		"RiggedFigure",
		"RiggedSimple",
		"scene",
		"SciFiHelmet",
		"SheenChair",
		"SheenCloth",
		"SheenDamask",
		"SheenHighHeel",
		"SimpleInstancing",
		"SimpleMeshes",
		"SimpleMorph",
		"SimpleSkin",
		"SimpleSparseAccessor",
		"SpecGlossVsMetalRough",
		"SpecularTest",
		"Sponza",
		"StainedGlassLamp",
		"Suzanne",
		"SuzanneMorphSparse",
		"TextureCoordinateTest",
		"TextureEncodingTest",
		"TextureLinearInterpolationTest",
		"TextureSettingsTest",
		"TextureTransformMultiTest",
		"TextureTransformTest",
		"ToyCar",
		"TransmissionRoughnessTest",
		"TransmissionSuzanne",
		"TransmissionTest",
		"Triangle",
		"TriangleWithoutIndices",
		"TwoSidedPlane",
		"Unicode??Test",
		"UnlitTest",
		"VC",
		"VertexColorTest",
		"WaterBottle",
		"XmpMetadataRoundedCube"
	};
}
