; Listing generated by Microsoft (R) Optimizing Compiler Version 19.33.31630.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__529D0EAA_concurrencysal@h DB 01H
__7EC34687_sal@h DB 01H
__35A2D2DF_vadefs@h DB 01H
__5F022EB5_vcruntime@h DB 01H
__BBDF6BA8_xkeycheck@h DB 01H
__7F8F4960_yvals_core@h DB 01H
__1B0272D9_corecrt@h DB 01H
__44420885_corecrt_stdio_config@h DB 01H
__AB601D8D_corecrt_wstdio@h DB 01H
__C1EC35D3_stdio@h DB 01H
__46E22952_cstdio DB 01H
__4DAFBCB9_stdint@h DB 01H
__CB505695_cstdint DB 01H
__0ED14FEE_winpackagefamily@h DB 01H
__F92EF742_winapifamily@h DB 01H
__22E515EB_sdkddkver@h DB 01H
__3F7A3B5F_excpt@h DB 01H
__79700276_stdarg@h DB 01H
__29F49F40_specstrings_undef@h DB 01H
__D0F42932_specstrings_strict@h DB 01H
__F00405FD_sdv_driverspecs@h DB 01H
__173E09CA_driverspecs@h DB 01H
__9A452361_specstrings@h DB 01H
__74484FB3_corecrt_wctype@h DB 01H
__1EC467ED_ctype@h DB 01H
__98517906_kernelspecs@h DB 01H
__D3497022_basetsd@h DB 01H
__61CC25A1_errno@h DB 01H
__74AC4223_vcruntime_string@h DB 01H
__E4C945B4_corecrt_memcpy_s@h DB 01H
__8EAFF484_corecrt_memory@h DB 01H
__6490AEC5_corecrt_wstring@h DB 01H
__E8295E1E_string@h DB 01H
__7FCB5136_guiddef@h DB 01H
__FF8A9E11_pshpack4@h DB 01H
__D5438902_poppack@h DB 01H
__FB07E2A3_pshpack2@h DB 01H
__F6906775_pshpack8@h DB 01H
__F9415CFA_pshpack1@h DB 01H
__E58C6F1C_apiset@h DB 01H
__A5C52262_ktmtypes@h DB 01H
__FBBA8F9D_winnt@h DB 01H
__A32D3D2C_minwindef@h DB 01H
__7D798299_windef@h DB 01H
__9AE108E9_apisetcconv@h DB 01H
__9CE53D2C_minwinbase@h DB 01H
__5D0AA210_apiquery2@h DB 01H
__4DD4E726_processenv@h DB 01H
__3575CC96_fileapi@h DB 01H
__8EA220E6_fileapifromapp@h DB 01H
__BF9B31FE_debugapi@h DB 01H
__C3AFE134_utilapiset@h DB 01H
__76F69E51_handleapi@h DB 01H
__7E63D784_errhandlingapi@h DB 01H
__FFA7003C_fibersapi@h DB 01H
__8971CECF_namedpipeapi@h DB 01H
__46C9D8A6_profileapi@h DB 01H
__98D4F0A3_heapapi@h DB 01H
__50EF2A88_ioapiset@h DB 01H
__92EA1464_synchapi@h DB 01H
__A53D8AED_interlockedapi@h DB 01H
__B506CAAF_processthreadsapi@h DB 01H
__FF735694_sysinfoapi@h DB 01H
__29589789_memoryapi@h DB 01H
__E9C7A663_enclaveapi@h DB 01H
__D035F9F7_threadpoollegacyapiset@h DB 01H
__C899130C_threadpoolapiset@h DB 01H
__E0441EE7_jobapi@h DB 01H
__CEF86838_jobapi2@h DB 01H
__35AC6B9A_wow64apiset@h DB 01H
__C8AE41A5_libloaderapi@h DB 01H
__CC9E232D_securitybaseapi@h DB 01H
__C9D0C9B8_namespaceapi@h DB 01H
__30FF9CAD_systemtopologyapi@h DB 01H
__4D358795_processtopologyapi@h DB 01H
__40446D10_securityappcontainer@h DB 01H
__3A952EDF_realtimeapiset@h DB 01H
__F4865F4B_winerror@h DB 01H
__53C1BD93_timezoneapi@h DB 01H
__1FFBEDBF_winbase@h DB 01H
__43D3FA34_wingdi@h DB 01H
__D24A7391_tvout@h DB 01H
__7713A6C8_winuser@h DB 01H
__0B345F71_datetimeapi@h DB 01H
__9AC6960C_winnls@h DB 01H
__973A40A8_stringapiset@h DB 01H
__CC46FEE2_wincontypes@h DB 01H
__97D70BE1_consoleapi@h DB 01H
__27EC5E18_consoleapi2@h DB 01H
__262E342F_consoleapi3@h DB 01H
__641DCD70_wincon@h DB 01H
__5A96C7A7_verrsrc@h DB 01H
__B69C6FF2_winver@h DB 01H
__7AEB8C37_reason@h DB 01H
__59F1A8A9_winreg@h DB 01H
__EE0E2B7F_wnnc@h DB 01H
__DCDB7054_winnetwk@h DB 01H
__EDC72EEB_cderr@h DB 01H
__95F9199D_dde@h DB 01H
__66427627_ddeml@h DB 01H
__957C29A0_dlgs@h DB 01H
__12EA15AF_lzexpand@h DB 01H
__62131F15_mmsyscom@h DB 01H
__47E68D49_mciapi@h DB 01H
__5D7DD356_mmiscapi@h DB 01H
__7223D2EF_mmiscapi2@h DB 01H
__A330DBB3_playsoundapi@h DB 01H
__601B366F_mmeapi@h DB 01H
__1134ADD5_timeapi@h DB 01H
__93F2265A_joystickapi@h DB 01H
__DF6EB4E3_mmsystem@h DB 01H
__BD641FCB_nb30@h DB 01H
__DF8704F0_rpcdcep@h DB 01H
__5C6CA7BB_rpcdce@h DB 01H
__853533C4_rpcnsi@h DB 01H
__2D2406C3_rpcnterr@h DB 01H
__64521D71_rpcasync@h DB 01H
__AADCBA08_rpc@h DB 01H
__19E26CFF_shellapi@h DB 01H
__1E9F31D3_winperf@h DB 01H
__832A4112_inaddr@h DB 01H
__32C6F875_winsock@h DB 01H
__7953A3F8_bcrypt@h DB 01H
__E4169492_ncrypt@h DB 01H
__AF3DDDC3_dpapi@h DB 01H
__D1E23BF2_wincrypt@h DB 01H
__82AB4779_winefs@h DB 01H
__1FE431C9_rpcnsip@h DB 01H
__2B741F2D_rpcsal@h DB 01H
__92623256_rpcndr@h DB 01H
__9C18532E_wtypesbase@h DB 01H
__EA2E1D6D_wtypes@h DB 01H
__7DDD9F45_winioctl@h DB 01H
__E550A843_winsmcrd@h DB 01H
__9809C1BA_winscard@h DB 01H
__EA174FA4_prsht@h DB 01H
__0E1BD114_winspool@h DB 01H
__45DED006_corecrt_malloc@h DB 01H
__13F5961F_stddef@h DB 01H
__FD6DBD68_corecrt_search@h DB 01H
__E2E33A61_corecrt_wstdlib@h DB 01H
__F3D99286_limits@h DB 01H
__6E5ACABA_stdlib@h DB 01H
__30B1AFDA_unknwnbase@h DB 01H
__328C1996_objidlbase@h DB 01H
__C4E06B6A_cguid@h DB 01H
__434718C5_combaseapi@h DB 01H
__DE6FDEF1_unknwn@h DB 01H
__CCE0BACC_objidl@h DB 01H
__8C7011E5_oaidl@h DB 01H
__2E0B7863_propidlbase@h DB 01H
__BF4CF2EC_coml2api@h DB 01H
__6D897344_oleidl@h DB 01H
__1129FC2C_servprov@h DB 01H
__757952E4_msxml@h DB 01H
__B1191D53_urlmon@h DB 01H
__404D1A47_propidl@h DB 01H
__A1C63593_objbase@h DB 01H
__C1B0A9CB_oleauto@h DB 01H
__24EAF61F_ole2@h DB 01H
__2B1843DA_commdlg@h DB 01H
__81DDEDE3_stralign@h DB 01H
__2134D1B4_winsvc@h DB 01H
__11C07376_mcx@h DB 01H
__577CE3E7_ime_cmodes@h DB 01H
__1E72C31E_imm@h DB 01H
__63AA7AF5_Windows@h DB 01H
__B06CCC37_Input@h DB 01H
__71BA79E8_Input@cpp DB 01H
msvcjmc	ENDS
PUBLIC	??_H@YAXPEAX_K1P6APEAX0@Z@Z			; `vector constructor iterator'
PUBLIC	??0sInputRegistered@RaisinEng@@QEAA@XZ		; RaisinEng::sInputRegistered::sInputRegistered
PUBLIC	??0sInputRegistered@RaisinEng@@QEAA@W4eINPUTKEY@1@P6AXH@Z@Z ; RaisinEng::sInputRegistered::sInputRegistered
PUBLIC	?_process_input@RaisinEng@@YAXH@Z		; RaisinEng::_process_input
PUBLIC	?_add_callback_input@RaisinEng@@YAXW4eINPUTKEY@1@P6AXH@Z@Z ; RaisinEng::_add_callback_input
PUBLIC	__JustMyCode_Default
PUBLIC	?m_inputs@RaisinEng@@3PAUsInputRegistered@1@A	; RaisinEng::m_inputs
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT ?m_inputs@RaisinEng@@3PAUsInputRegistered@1@A
_BSS	SEGMENT
?m_inputs@RaisinEng@@3PAUsInputRegistered@1@A DB 02000H DUP (?) ; RaisinEng::m_inputs
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_H@YAXPEAX_K1P6APEAX0@Z@Z DD imagerel $LN7
	DD	imagerel $LN7+172
	DD	imagerel $unwind$??_H@YAXPEAX_K1P6APEAX0@Z@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0sInputRegistered@RaisinEng@@QEAA@XZ DD imagerel $LN3
	DD	imagerel $LN3+76
	DD	imagerel $unwind$??0sInputRegistered@RaisinEng@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0sInputRegistered@RaisinEng@@QEAA@W4eINPUTKEY@1@P6AXH@Z@Z DD imagerel $LN3
	DD	imagerel $LN3+90
	DD	imagerel $unwind$??0sInputRegistered@RaisinEng@@QEAA@W4eINPUTKEY@1@P6AXH@Z@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__Em_inputs@RaisinEng@@YAXXZ DD imagerel ??__Em_inputs@RaisinEng@@YAXXZ
	DD	imagerel ??__Em_inputs@RaisinEng@@YAXXZ+67
	DD	imagerel $unwind$??__Em_inputs@RaisinEng@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_process_input@RaisinEng@@YAXH@Z DD imagerel $LN4
	DD	imagerel $LN4+109
	DD	imagerel $unwind$?_process_input@RaisinEng@@YAXH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_add_callback_input@RaisinEng@@YAXW4eINPUTKEY@1@P6AXH@Z@Z DD imagerel $LN3
	DD	imagerel $LN3+104
	DD	imagerel $unwind$?_add_callback_input@RaisinEng@@YAXW4eINPUTKEY@1@P6AXH@Z@Z
pdata	ENDS
;	COMDAT CRT$XCU
CRT$XCU	SEGMENT
?m_inputs$initializer$@RaisinEng@@3P6AXXZEA DQ FLAT:??__Em_inputs@RaisinEng@@YAXXZ ; RaisinEng::m_inputs$initializer$
CRT$XCU	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_add_callback_input@RaisinEng@@YAXW4eINPUTKEY@1@P6AXH@Z@Z DD 025061801H
	DD	01132318H
	DD	0700c0022H
	DD	0500a600bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_process_input@RaisinEng@@YAXH@Z DD 025051201H
	DD	010d2312H
	DD	07006001fH
	DD	05005H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__Em_inputs@RaisinEng@@YAXXZ DD 025050f01H
	DD	010a230fH
	DD	07003001dH
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0sInputRegistered@RaisinEng@@QEAA@W4eINPUTKEY@1@P6AXH@Z@Z DD 025051c01H
	DD	0117231cH
	DD	07010001dH
	DD	0500fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0sInputRegistered@RaisinEng@@QEAA@XZ DD 025051301H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_H@YAXPEAX_K1P6APEAX0@Z@Z DD 025052201H
	DD	011d2322H
	DD	07016001fH
	DD	05015H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?_add_callback_input@RaisinEng@@YAXW4eINPUTKEY@1@P6AXH@Z@Z
_TEXT	SEGMENT
$T1 = 200
_key$ = 272
_callback$ = 280
?_add_callback_input@RaisinEng@@YAXW4eINPUTKEY@1@P6AXH@Z@Z PROC ; RaisinEng::_add_callback_input, COMDAT
; File C:\dev\Raisin\Raisin\src\Raisin\Input\Input.cpp
; Line 14
$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	push	rsi
	push	rdi
	sub	rsp, 272				; 00000110H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__71BA79E8_Input@cpp
	call	__CheckForDebuggerJustMyCode
; Line 15
	mov	r8, QWORD PTR _callback$[rbp]
	mov	edx, DWORD PTR _key$[rbp]
	lea	rcx, QWORD PTR $T1[rbp]
	call	??0sInputRegistered@RaisinEng@@QEAA@W4eINPUTKEY@1@P6AXH@Z@Z ; RaisinEng::sInputRegistered::sInputRegistered
	movsxd	rcx, DWORD PTR _key$[rbp]
	imul	rcx, rcx, 16
	lea	rdx, OFFSET FLAT:?m_inputs@RaisinEng@@3PAUsInputRegistered@1@A ; RaisinEng::m_inputs
	lea	rdi, QWORD PTR [rdx+rcx]
	mov	rsi, rax
	mov	ecx, 16
	rep movsb
; Line 16
	lea	rsp, QWORD PTR [rbp+240]
	pop	rdi
	pop	rsi
	pop	rbp
	ret	0
?_add_callback_input@RaisinEng@@YAXW4eINPUTKEY@1@P6AXH@Z@Z ENDP ; RaisinEng::_add_callback_input
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?_process_input@RaisinEng@@YAXH@Z
_TEXT	SEGMENT
tv75 = 192
_key$ = 240
?_process_input@RaisinEng@@YAXH@Z PROC			; RaisinEng::_process_input, COMDAT
; File C:\dev\Raisin\Raisin\src\Raisin\Input\Input.cpp
; Line 6
$LN4:
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	push	rdi
	sub	rsp, 248				; 000000f8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__71BA79E8_Input@cpp
	call	__CheckForDebuggerJustMyCode
; Line 7
	movsxd	rax, DWORD PTR _key$[rbp]
	imul	rax, rax, 16
	lea	rcx, OFFSET FLAT:?m_inputs@RaisinEng@@3PAUsInputRegistered@1@A ; RaisinEng::m_inputs
	cmp	DWORD PTR [rcx+rax], 999		; 000003e7H
	je	SHORT $LN2@process_in
; Line 9
	movsxd	rax, DWORD PTR _key$[rbp]
	imul	rax, rax, 16
	lea	rcx, OFFSET FLAT:?m_inputs@RaisinEng@@3PAUsInputRegistered@1@A ; RaisinEng::m_inputs
	mov	rax, QWORD PTR [rcx+rax+8]
	mov	QWORD PTR tv75[rbp], rax
	mov	ecx, DWORD PTR _key$[rbp]
	call	QWORD PTR tv75[rbp]
$LN2@process_in:
; Line 11
	lea	rsp, QWORD PTR [rbp+216]
	pop	rdi
	pop	rbp
	ret	0
?_process_input@RaisinEng@@YAXH@Z ENDP			; RaisinEng::_process_input
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??__Em_inputs@RaisinEng@@YAXXZ
text$di	SEGMENT
??__Em_inputs@RaisinEng@@YAXXZ PROC			; RaisinEng::`dynamic initializer for 'm_inputs'', COMDAT
; File C:\dev\Raisin\Raisin\src\Raisin\Input\Input.h
; Line 148
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__B06CCC37_Input@h
	call	__CheckForDebuggerJustMyCode
	lea	r9, OFFSET FLAT:??0sInputRegistered@RaisinEng@@QEAA@XZ ; RaisinEng::sInputRegistered::sInputRegistered
	mov	r8d, 512				; 00000200H
	mov	edx, 16
	lea	rcx, OFFSET FLAT:?m_inputs@RaisinEng@@3PAUsInputRegistered@1@A ; RaisinEng::m_inputs
	call	??_H@YAXPEAX_K1P6APEAX0@Z@Z
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
??__Em_inputs@RaisinEng@@YAXXZ ENDP			; RaisinEng::`dynamic initializer for 'm_inputs''
text$di	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??0sInputRegistered@RaisinEng@@QEAA@W4eINPUTKEY@1@P6AXH@Z@Z
_TEXT	SEGMENT
this$ = 224
_key$ = 232
_callback$ = 240
??0sInputRegistered@RaisinEng@@QEAA@W4eINPUTKEY@1@P6AXH@Z@Z PROC ; RaisinEng::sInputRegistered::sInputRegistered, COMDAT
; File C:\dev\Raisin\Raisin\src\Raisin\Input\Input.h
; Line 142
$LN3:
	mov	QWORD PTR [rsp+24], r8
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__B06CCC37_Input@h
	call	__CheckForDebuggerJustMyCode
; Line 144
	mov	rax, QWORD PTR this$[rbp]
	mov	ecx, DWORD PTR _key$[rbp]
	mov	DWORD PTR [rax], ecx
; Line 145
	mov	rax, QWORD PTR this$[rbp]
	mov	rcx, QWORD PTR _callback$[rbp]
	mov	QWORD PTR [rax+8], rcx
; Line 146
	mov	rax, QWORD PTR this$[rbp]
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
??0sInputRegistered@RaisinEng@@QEAA@W4eINPUTKEY@1@P6AXH@Z@Z ENDP ; RaisinEng::sInputRegistered::sInputRegistered
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??0sInputRegistered@RaisinEng@@QEAA@XZ
_TEXT	SEGMENT
this$ = 224
??0sInputRegistered@RaisinEng@@QEAA@XZ PROC		; RaisinEng::sInputRegistered::sInputRegistered, COMDAT
; File C:\dev\Raisin\Raisin\src\Raisin\Input\Input.h
; Line 137
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__B06CCC37_Input@h
	call	__CheckForDebuggerJustMyCode
; Line 139
	mov	rax, QWORD PTR this$[rbp]
	mov	DWORD PTR [rax], 999			; 000003e7H
; Line 140
	mov	rax, QWORD PTR this$[rbp]
	mov	QWORD PTR [rax+8], 0
; Line 141
	mov	rax, QWORD PTR this$[rbp]
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
??0sInputRegistered@RaisinEng@@QEAA@XZ ENDP		; RaisinEng::sInputRegistered::sInputRegistered
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??_H@YAXPEAX_K1P6APEAX0@Z@Z
_TEXT	SEGMENT
tv72 = 192
tv66 = 192
tv67 = 200
__t$ = 240
__s$ = 248
__n$ = 256
__f$ = 264
??_H@YAXPEAX_K1P6APEAX0@Z@Z PROC			; `vector constructor iterator', COMDAT
$LN7:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 248				; 000000f8H
	lea	rbp, QWORD PTR [rsp+32]
$LN2@vector:
	mov	rax, QWORD PTR __n$[rbp]
	mov	QWORD PTR tv66[rbp], rax
	mov	rax, QWORD PTR __n$[rbp]
	dec	rax
	mov	QWORD PTR __n$[rbp], rax
	cmp	QWORD PTR tv66[rbp], 0
	jbe	SHORT $LN5@vector
	mov	DWORD PTR tv67[rbp], 1
	jmp	SHORT $LN6@vector
$LN5@vector:
	mov	DWORD PTR tv67[rbp], 0
$LN6@vector:
	cmp	DWORD PTR tv67[rbp], 0
	je	SHORT $LN3@vector
	mov	rax, QWORD PTR __f$[rbp]
	mov	QWORD PTR tv72[rbp], rax
	mov	rcx, QWORD PTR __t$[rbp]
	call	QWORD PTR tv72[rbp]
	mov	rax, QWORD PTR __s$[rbp]
	mov	rcx, QWORD PTR __t$[rbp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR __t$[rbp], rax
	jmp	SHORT $LN2@vector
$LN3@vector:
	lea	rsp, QWORD PTR [rbp+216]
	pop	rdi
	pop	rbp
	ret	0
??_H@YAXPEAX_K1P6APEAX0@Z@Z ENDP			; `vector constructor iterator'
_TEXT	ENDS
END
